### ISSUE TITLE
Just A Question

### ISSUE THREAD

**Issue by Tombez** [caiosm1005/Agar.io-bot-explosive#10]
I know some javascript, but how do you get the raw data about the cells in the game? Is it possible for me to do so as well? Does it have something to do with the nodes agario uses or are there global variables I can access? Thanks.

**Comment by caiosm1005** [comment]
You're better off asking @Apostolique. All I did was fork his project and customize his bot.

**Comment by Tombez** [comment]
Yeah, I did awhile ago but that project is dead.

**Comment by caiosm1005** [comment]
Just saw that. Recently Agar.io had some changes that broke all bots based on Apostolique's and it looks like he is not updating his project anymore.

I'd love to have pop-bot working again but I just don't have the time to update it.
