### ISSUE TITLE
Avoiding little cells

### ISSUE THREAD

**Issue by Drflash55** [caiosm1005/Agar.io-bot-explosive#2]
Sorry, I hit enter and didn't put a description...

When the bot goes to a virus and hides there so that it can disguise a virus underneath it, some other little cell will run itself into the bot and cause itself to get popped...
If you can put in an algorithm so that when it's above a virus, if there's a cell that get's way to close, the bot can move out of the way so that it doesn't run the risk of getting popped.

**Comment by caiosm1005** [comment]
@Drflash55 That would be pretty complicated to be made decently.

When a big cell gets close but doesn't try to eat the bot, it moves out of the cover slightly and then moves back, essentially blowing the cover.

If I did the same for small cells, that would happen way more frequently.

This brings up another issue, though: sometimes there's a small cell hiding underneath a virus. When the bot tries to cover the virus, it eats the smaller cell and also the virus by accident, splitting into many pieces.

**Comment by caiosm1005** [comment]
Current version of the bot avoids food/smaller cells that are close to the virus.
