### ISSUE TITLE
PopBot freezes when it is too big for virus

### ISSUE THREAD

**Issue by scriptinator** [caiosm1005/Agar.io-bot-explosive#5]
PopBot freezes when it is too big for virus.

**Comment by caiosm1005** [comment]
@scriptinator That's weird. Are you sure it wasn't stuck in between danger zones?

**Comment by Cybertrinn** [comment]
I had this problem too, in the console was logged 'mayday it's happening' then lots of:
We're too big for this virus - shooting some mass
VM99:1147 Uncaught ReferenceError: shoot is not defined

**Comment by clouedoc** [comment]
I have this problem too :'(

**Comment by caiosm1005** [comment]
Do you recall how much mass you had when that happened? Does it always happen when the cell is bigger than the virus?

**Comment by clouedoc** [comment]
I have found the solution : update AposLauncher :-)

**Comment by caiosm1005** [comment]
@Apostolique Could you shed some light on this?

I'm not sure how AposLauncher works (auto-updater and whatnot) and these guys apparently used PopBot with the default launcher, thus crashing when the bot tried to use the `shoot` function that only exists in my modified version.

**Comment by Apostolique** [comment]
I never did merge the shoot function. I guess I should.

**Comment by scriptinator** [comment]
Now, when virus is too big for bot, the bot will just try to go into the virus and then push out and then go back in. It never actually shoots any mass out

**Comment by caiosm1005** [comment]
@scriptinator Could you try that again with the latest AposLauncher?

**Comment by scriptinator** [comment]
Works perfectly now :)
